version: '1'
services:
  eurekaserver:
    image:  epharas/webshop-discovery-server:1.0.0
    ports:
      - "8082:8082"
    depends_on:
      - configserver
  configserver:
    image: epharas/webshop-config-server:1.0.0
    ports:
      - "8081:8081"
    environment:
      EUREKASERVER_PORT: 8082
      EUREKASERVER_URI: "http://eurekaserver:8082/eureka/"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  gatewayserver:
    image: epharas/webshop-gateway-server:1.0.0
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_PORT: 8081
      EUREKASERVER_PORT: 8082
      CONFIGSERVER_URI: "http://configserver:8081"
      EUREKASERVER_URI: "http://eurekaserver:8082/eureka/"
    depends_on:
      - configserver
      - eurekaserver
  database:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgr@s
      - POSTGRES_DB=eagle_eye_local
  clientservice:
    image: epharas/webshop-client:1.0.0
    ports:
      - "8082:8082"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8082"
      ES_PORT:           9200
      DATABASE_PORT:     3306
      CONFIGSERVER_PORT: 8081
      EUREKASERVER_PORT: 8082
      AUTHSERVER_PORT:   8084
      CONFIGSERVER_URI: "http://configserver:8081"
      EUREKASERVER_URI: "http://eurekaserver:8082/eureka/"
      AUTHSERVER_URI:   "http://authenticationservice:8084/auth/user"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    depends_on:
      - configserver
      - eurekaserver
      - gatewayserver
      - database
      - authenticationservice
      - management
  management:
    image: epharas/webshop-management:1.0.0
    ports:
      - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      DATABASE_PORT:     3306
      CONFIGSERVER_PORT: 8081
      EUREKASERVER_PORT: 8082
      AUTHSERVER_PORT:   8084
      CONFIGSERVER_URI: "http://configserver:8081"
      EUREKASERVER_URI: "http://eurekaserver:8082/eureka/"
      AUTHSERVER_URI:   "http://authenticationservice:8084/auth/user"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    depends_on:
      - configserver
      - eurekaserver
      - gatewayserver
      - database
      - authenticationservice
  authenticationservice:
      image: epharas/webshop-authentication:1.0.0
      ports:
        - "8084:8084"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8084"
        DATABASE_PORT:     3306
        CONFIGSERVER_PORT: 8081
        EUREKASERVER_PORT: 8082
        CONFIGSERVER_URI: "http://configserver:8081"
        EUREKASERVER_URI: "http://eurekaserver:8082/eureka/"
        ENCRYPT_KEY:       "IMSYMMETRIC"
      depends_on:
        - configserver
        - eurekaserver
        - gatewayserver